name: build-deploy-prerelease

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x 
        config-file: nuget.config
        source-url: https://nuget.pkg.github.com/Buerkert/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build with dotnet
      run: dotnet build -c Release --version-suffix build.${{ github.run_number }}
    - name: Run unit tests
      run: dotnet test
    - name: Pack
      run: dotnet pack -c Release --version-suffix build.${{ github.run_number }} -o package
    - name: Push generated package to GitHub registry
      run: dotnet nuget push package\Buerkert.NLua.*.*nupkg --api-key ${{secrets.GITHUB_TOKEN}}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: NLua
        path: NLua\bin\Release\*nupkg
