name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: nuget restore
      run: nuget restore NLua.Net45.sln
    - name: Build with dotnet
      run: dotnet msbuild NLua.Net45.sln -p:Configuration=Release -r
    #- name: Run unit tests
    #  run: packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe tests\NLuaTest.dll --work=Run\Release\net45
    - name: Pack nuget package
      run: nuget pack NLua.nuspec -OutputDirectory Run\Release\net45
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: NLua
        path: Run\Release\net45
